// ===========================
// 보유종목 KPI 모니터링 데이터
// 나무늘보 투자조합
//
// [분기별 갱신 안내]
//  - 최신값이 없으면 value: null 로 둡니다. 추정치를 채우지 마세요. 화면에는 "—" 로 표시됩니다.
//  - cadence 는 배열입니다: '분기' | '반기' | '연간' | '이벤트'
//  - nature 는 '정량' | '정성'
//  - 값을 갱신하면 해당 종목의 updated 날짜도 함께 고쳐주세요.
// ===========================
const KPI_DATA = {
  holdings: [
    // -------------------------------------------------- ASML
    {
      ticker: 'ASML',
      name: 'ASML Holding',
      moat: 'EUV 독점. 수요와 반복매출 확인이 핵심.',
      updated: '2026-09-17',
      kpis: [
        {
          rank: 1,
          name: '고객 capex·EUV 증설 계획',
          why: '수요 선행 지표',
          value: null,
          asOf: null,
          source: 'TSMC·마이크론·인텔·SK하이닉스·삼성 IR',
          cadence: ['분기'],
          nature: '정량',
        },
        {
          rank: 2,
          name: 'Installed Base Management 매출',
          why: '반복매출, 사이클 방어력',
          value: null,
          asOf: null,
          source: 'ASML 분기 실적',
          cadence: ['분기'],
          nature: '정량',
        },
        {
          rank: 3,
          name: '백로그 / 가이던스',
          why: '매출 가시성',
          value: '백로그 €38.8B',
          asOf: '2025년 말',
          source: 'ASML 연간 실적',
          cadence: ['연간', '분기'],
          cadenceNote: '백로그는 연간, 가이던스는 분기',
          nature: '정량',
        },
        {
          rank: 4,
          name: 'High-NA 채택',
          why: 'ASP 상승, 가격결정력',
          value: null,
          asOf: null,
          source: '컨퍼런스콜',
          cadence: ['분기'],
          nature: '정성',
        },
        {
          rank: 5,
          name: '매출총이익률',
          why: '가격결정력, High-NA 희석',
          value: '가이던스 51~53%',
          asOf: '2026년 1분기',
          source: 'ASML 분기 실적',
          cadence: ['분기'],
          nature: '정량',
        },
        {
          rank: 6,
          name: '중국 매출 비중',
          why: '리스크 — 지역 집중도',
          value: '2026년 약 20% 전망',
          asOf: '2026년 전망',
          source: 'ASML 실적',
          cadence: ['분기'],
          nature: '정량',
        },
        {
          rank: 7,
          name: '대체기술 동향',
          why: '리스크 — EUV 해자 침식 여부',
          value: null,
          asOf: null,
          source: 'SPIE·imec',
          cadence: ['이벤트'],
          nature: '정성',
        },
      ],
      cautions: [
        '2026년 1분기부터 분기 수주 공시 중단. 마지막 공시는 2025년 4분기 €13.2B(EUV €7.4B).',
        '노드별 EUV 레이어 수는 공식 수치 없음(2차 자료).',
      ],
    },

    // -------------------------------------------------- WST
    {
      ticker: 'WST',
      name: 'West Pharmaceutical Services',
      moat: 'HVP 믹스와 가격결정력이 핵심. West Vantage(구 CMO 부문)는 저마진.',
      updated: '2026-09-17',
      kpis: [
        {
          rank: 1,
          name: 'HVP Components 성장률·매출 비중',
          why: '해자와 마진의 원천',
          value: '유기 +18.4%, 매출의 49%',
          asOf: '2026년 2분기',
          source: '실적 발표',
          cadence: ['분기'],
          nature: '정량',
        },
        {
          rank: 2,
          name: '가격 기여분',
          why: '가격결정력 직접 확인',
          value: '가격 $30.3M vs 물량·믹스 $67.0M',
          asOf: '2026년 2분기',
          source: '10-Q',
          cadence: ['분기'],
          nature: '정량',
        },
        {
          rank: 3,
          name: '매출총이익률',
          why: '믹스 개선 결과',
          value: '37.7%, +200bp',
          asOf: '2026년 2분기',
          source: '실적 발표',
          cadence: ['분기'],
          nature: '정량',
        },
        {
          rank: 4,
          name: '바이오로직스·Annex 1 진척',
          why: '다년간 믹스 개선 동력',
          value: '바이오로직스 유기 +29% / Annex 1 FY26 성장 기여 약 200bp 예상',
          asOf: '2026년 2분기',
          source: '실적 발표·IR',
          cadence: ['분기'],
          nature: '정량',
        },
        {
          rank: 5,
          name: 'capex 전환 효율·FCF',
          why: '증설이 HVP 성장으로 연결되는지',
          value: 'capex $285.9M, FCF $468.9M',
          asOf: '2025년',
          source: '10-K',
          cadence: ['분기', '연간'],
          nature: '정량',
        },
        {
          rank: 6,
          name: 'GLP-1·West Vantage 집중도',
          why: '고객 의존 리스크',
          value: 'GLP-1 매출의 18%',
          asOf: '2026년 1분기',
          source: 'IR 자료',
          cadence: ['분기', '이벤트'],
          nature: '정량',
        },
      ],
      cautions: [
        'Standard Products 유기성장 +0.7%(2026년 2분기). HVP와의 격차 추적.',
        '2분기 HVP Delivery Devices 성장에 SmartDose 3.5mL 거래 종결(2026년 7월) 전 선수요 포함 → 하반기 기저효과.',
        '2분기 West Vantage 유기성장 +0.8%는 사이버 사고 영향(일회성).',
      ],
    },

    // -------------------------------------------------- WM
    {
      ticker: 'WM',
      name: 'Waste Management',
      moat: '매립지 에어스페이스와 수직계열화 기반의 가격결정력.',
      updated: '2026-09-17',
      kpis: [
        {
          rank: 1,
          name: 'Core price vs C&D yield 격차',
          why: '가격 인상이 이탈로 새는지',
          value: '5.7% vs 3.6%',
          asOf: '2026년 2분기',
          source: '실적 발표',
          cadence: ['분기'],
          nature: '정량',
        },
        {
          rank: 2,
          name: 'Price-to-cost spread·C&D EBITDA 마진',
          why: '가격이 비용을 앞서는지',
          value: '영업비용/매출 59.2%',
          asOf: '2026년 2분기',
          source: '실적 발표',
          cadence: ['분기'],
          nature: '정량',
        },
        {
          rank: 3,
          name: '매립·특수폐기물 물량',
          why: '수요와 경기 선행',
          value: '산불 제외 매립 +1.7%, 특수폐기물 +4.5%',
          asOf: '2026년 2분기',
          source: '실적 발표·콜',
          cadence: ['분기'],
          nature: '정량',
        },
        {
          rank: 4,
          name: 'FCF·capex 정상화',
          why: '투자 사이클 종료 확인',
          value: null,
          asOf: null,
          source: '실적 발표',
          cadence: ['분기'],
          nature: '정량',
        },
        {
          rank: 5,
          name: '에어스페이스 잔여 수명·내부화율',
          why: '해자의 실체',
          value: null,
          asOf: null,
          source: '10-K, IR 자료',
          cadence: ['연간'],
          nature: '정량',
        },
        {
          rank: 6,
          name: '헬스케어 통합·재활용·RNG',
          why: '보조(B급 이하, 원자재 민감)',
          value: '헬스케어 조정 EBITDA +$11M',
          asOf: '2026년 2분기',
          source: '실적 발표',
          cadence: ['분기'],
          nature: '정량',
        },
      ],
      cautions: [
        'C&D 물량 -1.8%(산불 제외 -0.4%), 일부는 저마진 주거용 계약 의도적 정리.',
        '2026년 매출 가이던스를 $26.275~26.475B로 하향(물량 부진). 회사는 하반기 물량 보합, core price 연말 5.5% 이상 예상.',
      ],
    },

    // -------------------------------------------------- LSEG
    {
      ticker: 'LSEG',
      name: 'London Stock Exchange Group',
      moat: 'LCH 청산·FTSE Russell은 A급, D&A는 B급(AI 영향 감시 대상).',
      updated: '2026-09-17',
      kpis: [
        {
          rank: 1,
          name: 'ASV 성장률·구독 사업 성장률',
          why: '구독매출 선행 지표',
          value: 'ASV 6.1%(2분기 말), 구독 +6.3%, 연간 목표 약 6.5%',
          asOf: '2026년 상반기',
          source: '반기 실적',
          cadence: ['분기', '반기'],
          nature: '정량',
        },
        {
          rank: 2,
          name: 'Workflows vs Data & Feeds 격차',
          why: 'AI가 D&A를 약화/강화하는지',
          value: 'Workflows +2.8% vs Data & Feeds +7.5%',
          asOf: '2026년 상반기',
          source: '반기 실적',
          cadence: ['분기', '반기'],
          nature: '정량',
        },
        {
          rank: 3,
          name: 'SwapClear 명목금액·LCH 매출',
          why: 'A급 청산 해자',
          value: 'SwapClear +29%, ForexClear +45%',
          asOf: '2026년 상반기',
          source: '반기 실적',
          cadence: ['분기', '반기'],
          nature: '정량',
        },
        {
          rank: 4,
          name: 'FTSE Russell 구독형 성장률',
          why: 'A급 지수 해자(자산연동형과 분리)',
          value: 'FTSE Russell 전체 +9.1%',
          asOf: '2026년 상반기',
          source: '반기 실적',
          cadence: ['분기', '반기'],
          nature: '정량',
        },
        {
          rank: 5,
          name: '조정 EBITDA 마진·주당 FCF',
          why: '운영 레버리지',
          value: '마진 52.7%, 주당 FCF +37%',
          asOf: '2026년 상반기',
          source: '반기 실적',
          cadence: ['반기'],
          nature: '정량',
        },
        {
          rank: 6,
          name: 'API·MCP 사용량',
          why: 'AI 수익화 선행',
          value: 'API +33%, MCP 호출 5~6월 5배',
          asOf: '2026년 상반기',
          source: '컨퍼런스콜',
          cadence: ['반기'],
          nature: '정성',
        },
      ],
      cautions: [
        'AI 매출 비중은 별도 공시 없음. 경영진이 단기 AI 매출 기대를 낮춤.',
        '상반기 마진 개선 260bp 중 140bp는 SwapClear 수익배분 계약 변경 효과(반복성 구분 필요).',
        '2026년 가이던스: 유기성장 7~7.5%, 마진 약 100bp 개선, FCF £2.7B 이상.',
      ],
    },
  ],
};
